### ISSUE TITLE
suds import module is broken

### ISSUE THREAD

**Issue by JohnTheodore** [metagriffin/dnssync#2]
When I run 'dnssync' I get some error saying powerdns driver is unknown/unavailable. I debugged it to the 'suds' library that gets installed. On the latest mac version with the default 2.7.11 python, suds doesn't seem to be the right library. This import fails:

`from suds.client import Client`

Though I uninstalled suds, and installed suds-jurko, and this suceeds.

**Comment by metagriffin** [comment]
thanks for finding `suds-jurko` -- i've updated the dependency and released to 0.2.4. thanks for the feedback.
