### ISSUE TITLE
Invalid user fails with unrelated message

### ISSUE THREAD

**Issue by JohnTheodore** [metagriffin/dnssync#4]
I am getting this: `AttributeError: 'listZones_response' object has no attribute 'Zones'`.. with some debug output. 

Though if I debug, I actually see: (listZones_response){
   code = 200
   description = "INVALID_USER"
 }

It would be nice if the credentials are wrong.. that it said so clearly without needing to debug into what code gets executed where.

**Comment by metagriffin** [comment]
indeed, i agree!

fixed in bbe9ef1579d83427cf129823fb2412d6abebcf36 and added to release 0.2.4.

thanks for the feedback.
